version: '3.1'

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
